
version: '2' # Use 3 instead ??

services:

    ui:
        image: # node
        restart: always
#        environment: # doesn't work on Scaleway
#            - PUID=1000
#            - PGID=1000
        ports:
            - 3000:3000
        volumes:
            - type: volume
            source: havistin_storage
            target: /storage

    volumes:
        havistin_storage: